name: Generate coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

          #      - name: Install webdrivers
          #        run: sude apt-get -r install firefox-geckodriver  google-chrome-stable

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51.0-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install JavaScript Dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Run the tests
        run: yarn test

      - name: Generate coverage file
        if: (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-t 1200'

      - name: Upload to Codecov
        if: (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        uses: codecov/codecov-action@v1

      - name: generate documentation
        if: (github.repository == 'mCaptcha/browser')
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --workspace --all-features
